target 'YouShop' do
  use_frameworks!
  platform :ios, '16'
  
  # https://github.com/elai950/AlertToast
  pod 'AlertToast', '1.3.7'
  # https://github.com/airbnb/lottie-ios
  pod 'lottie-ios', '4.0.1'
  # https://github.com/SwiftGen/SwiftGen
  pod 'SwiftGen', '6.6.2'
  # https://github.com/realm/realm-swift
  pod 'RealmSwift', '10.33.0'
  # https://github.com/realm/SwiftLint
  pod 'SwiftLint'
  # https://github.com/nicklockwood/SwiftFormat
  pod 'SwiftFormat/CLI'
  # https://github.com/onevcat/Kingfisher
  pod 'Kingfisher'
  # https://github.com/SVGKit/SVGKit
  pod 'SVGKit'
  # https://github.com/yonat/MultiSlider
  pod 'MultiSlider'
  
  pod 'shared', :path => '../../../shared'
end
