name: ci

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material

      - name: Data
        run: |
          [ -d docs/data ] && rm -r docs/data
          cp -r data docs/data

      - name: Dokka
        run: |
          [ -d docs/dokka ] && rm -r docs/dokka
          mkdir docs/dokka
          gradle dokkaHtmlMultiModule --stacktrace

      - name: Build site
        run: |
          mkdocs gh-deploy --force